import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { PageHeader } from '../../components/layout/PageHeader';
import { KPICard } from '../../components/ui/KPICard';
import { api } from '../../lib/api';
import {
  Activity,
  Droplet,
  DollarSign,
  TrendingUp,
  BarChart2,
  PieChart as PieIcon,
  ShieldAlert,
} from 'lucide-react';
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
} from 'recharts';

export const AnalyticsPage: React.FC = () => {
  // Fetch KPI data
  const { data: kpis, isLoading: isKpisLoading } = useQuery({
    queryKey: ['analytics-kpis'],
    queryFn: () => api.get<any>('/analytics/kpis'),
  });

  // Fetch cost breakdown
  const { data: costBreakdown, isLoading: isBreakdownLoading } = useQuery({
    queryKey: ['analytics-breakdown'],
    queryFn: () => api.get<any>('/analytics/cost-breakdown'),
  });

  // Fetch costliest vehicles
  const { data: costliestVehicles, isLoading: isCostliestLoading } = useQuery({
    queryKey: ['analytics-costliest'],
    queryFn: () => api.get<any[]>('/analytics/costliest-vehicles'),
  });

  // Fetch Vehicle ROI
  const { data: vehicleROI, isLoading: isRoiLoading } = useQuery({
    queryKey: ['analytics-roi'],
    queryFn: () => api.get<any[]>('/analytics/vehicle-roi'),
  });

  // Fetch Trends
  const { data: trends, isLoading: isTrendsLoading } = useQuery({
    queryKey: ['analytics-trends'],
    queryFn: () => api.get<any[]>('/analytics/trends'),
  });

  // Process Pie Chart Data (Cost Breakdown)
  const pieData = costBreakdown
    ? [
        { name: 'Fuel', value: costBreakdown.fuel, color: '#2563eb' }, // blue-600
        { name: 'Maintenance', value: costBreakdown.maintenance, color: '#16a34a' }, // green-600
        { name: 'Toll', value: costBreakdown.expenses.toll, color: '#eab308' }, // yellow-500
        { name: 'Parking', value: costBreakdown.expenses.parking, color: '#ec4899' }, // pink-500
        { name: 'Repair (Exp)', value: costBreakdown.expenses.repair, color: '#a855f7' }, // purple-500
        { name: 'Maint (Exp)', value: costBreakdown.expenses.maintenance, color: '#f97316' }, // orange-500
        { name: 'Insurance', value: costBreakdown.expenses.insurance, color: '#06b6d4' }, // cyan-500
        { name: 'Other', value: costBreakdown.expenses.other, color: '#64748b' }, // slate-500
      ].filter((item) => item.value > 0)
    : [];

  return (
    <div className="space-y-6">
      <PageHeader
        title="Intelligence & Analytics"
        description="Comprehensive dashboard displaying fleet utilization, fuel efficiency, ROI, and operational cost breakdowns"
      />

      {/* KPI Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <KPICard
          title="Fleet Utilization"
          value={isKpisLoading ? '...' : `${kpis?.fleetUtilization || 0}%`}
          description={
            isKpisLoading
              ? 'Loading...'
              : `${kpis?.vehiclesOnTrip || 0} of ${kpis?.activeVehicles || 0} active vehicles on trip`
          }
          icon={Activity}
          loading={isKpisLoading}
        />
        <KPICard
          title="Fuel Efficiency"
          value={isKpisLoading ? '...' : `${kpis?.fuelEfficiency || 0} km/L`}
          description="Average kilometers traveled per liter of fuel"
          icon={Droplet}
          loading={isKpisLoading}
        />
        <KPICard
          title="Total Operational Cost"
          value={
            isKpisLoading
              ? '...'
              : `$${Number(kpis?.totalOperationalCost || 0).toLocaleString(undefined, {
                  maximumFractionDigits: 0,
                })}`
          }
          description="Aggregated fuel + maintenance + other operational expenses"
          icon={DollarSign}
          loading={isKpisLoading}
        />
        <KPICard
          title="Attributed Revenue"
          value={
            isKpisLoading
              ? '...'
              : `$${Number(kpis?.totalRevenue || 0).toLocaleString(undefined, {
                  maximumFractionDigits: 0,
                })}`
          }
          description="Cumulative billing generated by completed dispatch trips"
          icon={TrendingUp}
          loading={isKpisLoading}
        />
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Cost vs Revenue Trends */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <BarChart2 className="h-5 w-5 text-brand-600" />
            <h3 className="font-bold text-slate-800 text-lg">Financial Performance Trends</h3>
          </div>
          {isTrendsLoading ? (
            <div className="h-80 flex items-center justify-center text-slate-500 animate-pulse">
              Loading financial trends...
            </div>
          ) : !trends || trends.length === 0 ? (
            <div className="h-80 flex items-center justify-center text-slate-400">
              No historical trend data recorded.
            </div>
          ) : (
            <div className="h-80 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={trends} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#16a34a" stopOpacity={0.2} />
                      <stop offset="95%" stopColor="#16a34a" stopOpacity={0} />
                    </linearGradient>
                    <linearGradient id="colorCost" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#ef4444" stopOpacity={0.2} />
                      <stop offset="95%" stopColor="#ef4444" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                  <XAxis dataKey="month" stroke="#94a3b8" fontSize={12} />
                  <YAxis stroke="#94a3b8" fontSize={12} />
                  <Tooltip formatter={(value) => [`$${Number(value).toLocaleString()}`, '']} />
                  <Legend verticalAlign="top" height={36} />
                  <Area
                    type="monotone"
                    name="Revenue"
                    dataKey="revenue"
                    stroke="#16a34a"
                    fillOpacity={1}
                    fill="url(#colorRevenue)"
                    strokeWidth={2}
                  />
                  <Area
                    type="monotone"
                    name="Operating Cost"
                    dataKey="totalCost"
                    stroke="#ef4444"
                    fillOpacity={1}
                    fill="url(#colorCost)"
                    strokeWidth={2}
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          )}
        </div>

        {/* Cost Breakdown Pie Chart */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <PieIcon className="h-5 w-5 text-brand-600" />
            <h3 className="font-bold text-slate-800 text-lg">Operational Expenses Breakdown</h3>
          </div>
          {isBreakdownLoading ? (
            <div className="h-80 flex items-center justify-center text-slate-500 animate-pulse">
              Loading cost breakdown...
            </div>
          ) : pieData.length === 0 ? (
            <div className="h-80 flex items-center justify-center text-slate-400">
              No operating costs recorded.
            </div>
          ) : (
            <div className="h-80 flex flex-col md:flex-row items-center justify-center">
              <div className="h-64 w-full md:w-1/2">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={pieData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={80}
                      paddingAngle={4}
                      dataKey="value"
                    >
                      {pieData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip formatter={(value) => [`$${Number(value).toLocaleString()}`, '']} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="w-full md:w-1/2 space-y-2 max-h-64 overflow-y-auto px-4">
                {pieData.map((item, index) => (
                  <div key={index} className="flex justify-between items-center text-sm">
                    <div className="flex items-center gap-2">
                      <div
                        className="w-3 h-3 rounded-full"
                        style={{ backgroundColor: item.color }}
                      />
                      <span className="text-slate-600 font-medium">{item.name}</span>
                    </div>
                    <span className="font-bold text-slate-800">
                      ${Number(item.value).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Costliest Vehicles & ROI Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Costliest Vehicles Chart */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm lg:col-span-1">
          <div className="flex items-center gap-2 mb-4">
            <ShieldAlert className="h-5 w-5 text-red-500" />
            <h3 className="font-bold text-slate-800 text-lg">Top 5 Costliest Vehicles</h3>
          </div>
          {isCostliestLoading ? (
            <div className="h-80 flex items-center justify-center text-slate-500 animate-pulse">
              Loading cost records...
            </div>
          ) : !costliestVehicles || costliestVehicles.length === 0 ? (
            <div className="h-80 flex items-center justify-center text-slate-400">
              No vehicle operating costs logged.
            </div>
          ) : (
            <div className="h-80 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  data={costliestVehicles}
                  layout="vertical"
                  margin={{ top: 10, right: 10, left: 10, bottom: 5 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                  <XAxis type="number" stroke="#94a3b8" fontSize={10} />
                  <YAxis
                    type="category"
                    dataKey="registrationNumber"
                    stroke="#94a3b8"
                    fontSize={11}
                    width={70}
                  />
                  <Tooltip formatter={(value) => [`$${Number(value).toLocaleString()}`, 'Cost']} />
                  <Bar dataKey="totalCost" fill="#dc2626" radius={[0, 4, 4, 0]} barSize={20} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}
        </div>

        {/* Vehicles ROI Table */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm lg:col-span-2 overflow-hidden flex flex-col">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="h-5 w-5 text-brand-600" />
            <h3 className="font-bold text-slate-800 text-lg">Vehicle ROI Performance</h3>
          </div>
          {isRoiLoading ? (
            <div className="flex-1 py-12 text-center text-slate-500 animate-pulse">
              Loading ROI parameters...
            </div>
          ) : !vehicleROI || vehicleROI.length === 0 ? (
            <div className="flex-1 py-12 text-center text-slate-400">
              No vehicles available.
            </div>
          ) : (
            <div className="flex-1 overflow-x-auto">
              <table className="w-full text-left border-collapse text-sm">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-semibold">
                    <th className="px-4 py-3">Vehicle</th>
                    <th className="px-4 py-3">Acquisition Cost</th>
                    <th className="px-4 py-3">Revenue</th>
                    <th className="px-4 py-3">Operating Cost</th>
                    <th className="px-4 py-3">Net Profit</th>
                    <th className="px-4 py-3 text-right">ROI (%)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-slate-700">
                  {vehicleROI.map((v) => (
                    <tr key={v.id} className="hover:bg-slate-50/50">
                      <td className="px-4 py-3 font-mono font-bold text-slate-900">
                        {v.registrationNumber}
                        <span className="block text-xs font-normal text-slate-500 font-sans">
                          {v.name}
                        </span>
                      </td>
                      <td className="px-4 py-3">${v.acquisitionCost.toLocaleString()}</td>
                      <td className="px-4 py-3 text-green-600 font-semibold">
                        +${v.revenue.toLocaleString()}
                      </td>
                      <td className="px-4 py-3 text-red-600">
                        -${v.operatingCost.toLocaleString()}
                      </td>
                      <td
                        className={`px-4 py-3 font-semibold ${
                          v.netProfit >= 0 ? 'text-green-600' : 'text-red-600'
                        }`}
                      >
                        {v.netProfit >= 0 ? '+' : '-'}${Math.abs(v.netProfit).toLocaleString()}
                      </td>
                      <td
                        className={`px-4 py-3 text-right font-extrabold text-base whitespace-nowrap ${
                          v.roi >= 0 ? 'text-green-600' : 'text-red-600'
                        }`}
                      >
                        {v.roi}%
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
